# Generated by Django 3.2.8 on 2021-12-17 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, validators=[django.core.validators.MinLengthValidator(17)])),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('trim', models.CharField(max_length=20)),
                ('drive_type', models.CharField(choices=[('FWD', 'Front Wheel Drive'), ('RWD', 'Rear Wheel Drive'), ('AWD', 'All Wheel Drive'), ('4x4', 'Four Wheel Drive')], default='FWD', max_length=3)),
            ],
        ),
    ]
