# Generated by Django 3.2.8 on 2021-12-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20211223_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='miles_current',
            field=models.IntegerField(default=20000),
            preserve_default=False,
        ),
    ]
