# Generated by Django 3.2.8 on 2021-12-29 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_item', '0002_maintenanceitem_vehicle_type'),
        ('maintenance_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='maintenance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maintenance_item.maintenanceitem'),
            preserve_default=False,
        ),
    ]
