# Generated by Django 3.2.8 on 2021-12-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='log_title',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
