# Generated by Django 3.2.8 on 2021-12-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_name', models.CharField(max_length=100)),
                ('maintenance_miles', models.IntegerField(blank=True)),
                ('maintenance_periodicity', models.CharField(blank=True, max_length=20)),
                ('maintenance_description', models.CharField(max_length=300)),
            ],
        ),
    ]
