# Generated by Django 3.2.8 on 2021-12-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20211223_0817'),
        ('maintenance_item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceitem',
            name='vehicle_type',
            field=models.ManyToManyField(to='vehicle.VehicleType'),
        ),
    ]
