# Generated by Django 3.2.8 on 2021-12-22 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20211222_1434'),
        ('maintenance_item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceitem',
            name='vehicle_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehicletype'),
        ),
    ]
