# Generated by Django 3.2.8 on 2022-01-01 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_vehicle_miles_current'),
        ('maintenance_item', '0002_maintenanceitem_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceitem',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='maintenanceitem',
            name='vehicle_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehicletype'),
        ),
    ]
